### ISSUE TITLE
Should provide a mechanism to hint bot to stop transmit current message

### ISSUE THREAD

**Issue by caasi** [caasi/teleirc#5]
朋友提到也許可以用一些 prefix 提示 bot 不要轉發訊息，例如 `(小聲)` ，甚至加上強調用的功能，像是 `(大聲)` 。

老實一點的做法可能是提供 `/local` 和 `/yell` 指令，不過大小聲比較在地化 XD

**Comment by caasi** [comment]
上游在 [5186207](https://github.com/FruitieX/teleirc/commit/5186207a20898f84656711880975488bd8766396) 加上了黑名單 regexp ，相當於已經實現此功能。

**Comment by kuanyui** [comment]
太難打了啦 (小聲)
`\b/local\b` 或者乾脆 `/////+` 如何？

**Comment by caasi** [comment]
`/////+` 要是 `/` 少打或是多打不就... XDDDD

`#local` 如何？

**Comment by kuanyui** [comment]
大大決定啦XD 只有我覺得很難打？反正因為/////不小心漏掉一兩個訊息也不會造成太大的傷害 (小聲)

**Comment by caasi** [comment]
那就加上 `/////` ，秘密指令～

**Comment by kuanyui** [comment]
欸嘿嘿！祕密！
